# Generated by Django 4.2.7 on 2024-11-21 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Services",
            new_name="Contact",
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"verbose_name_plural": "Обратный связ"},
        ),
    ]
