# Generated by Django 4.2.7 on 2024-11-21 19:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_rename_services_contact_alter_contact_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "title_intrested",
                    models.CharField(
                        max_length=155, verbose_name="Заголовка заинтересованный"
                    ),
                ),
                (
                    "descriptions_intrested",
                    ckeditor.fields.RichTextField(
                        verbose_name="Описание заинтересованный"
                    ),
                ),
                (
                    "title_services",
                    models.CharField(max_length=155, verbose_name="Заголовка услуги"),
                ),
            ],
            options={
                "verbose_name_plural": "О нас",
            },
        ),
    ]
