# Generated by Django 4.2.7 on 2024-11-21 19:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_about"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="descriptions_intrested",
        ),
        migrations.AddField(
            model_name="about",
            name="our_desctiptions_history",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Описание Историй"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="our_history",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка Историй"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="our_locations",
            field=models.CharField(
                default=1, max_length=155, verbose_name="Заголовка локаций"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="about",
            name="our_locations_descriptions",
            field=ckeditor.fields.RichTextField(
                default=1, verbose_name="Описание локаций"
            ),
            preserve_default=False,
        ),
    ]
