# Generated by Django 4.2.7 on 2024-11-21 20:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_services"),
    ]

    operations = [
        migrations.CreateModel(
            name="Base",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "title_parking",
                    models.CharField(max_length=155, verbose_name="Заголовка парковки"),
                ),
                (
                    "title_choices",
                    models.CharField(max_length=155, verbose_name="Заголовка Выбора"),
                ),
            ],
            options={
                "verbose_name_plural": "Настройка Главной страницы",
            },
        ),
    ]
