# Generated by Django 4.2.7 on 2024-11-21 23:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_choices_landlord_delete_list"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                ("price", models.CharField(max_length=155, verbose_name="Цена")),
            ],
            options={
                "verbose_name_plural": "Дополнительные опции",
            },
        ),
        migrations.CreateModel(
            name="TypeCar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "parking_space",
                    models.CharField(max_length=155, verbose_name="Парковочное место"),
                ),
                (
                    "parking_availble",
                    models.CharField(max_length=155, verbose_name="Доступные места"),
                ),
                ("price", models.CharField(max_length=155, verbose_name="Цена")),
            ],
            options={
                "verbose_name_plural": "Типы Транспорта",
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_date", models.DateTimeField(verbose_name="вход дата")),
                ("entry_time", models.DateTimeField(verbose_name="Время входа")),
                ("exit_data", models.DateTimeField(verbose_name="выход дата")),
                ("exit_time", models.DateTimeField(verbose_name="выход время")),
                (
                    "select_parking",
                    models.CharField(
                        choices=[("Чуй", "Чуй"), ("Ош", "Ош"), ("Бишкек", "Бишкек")],
                        max_length=155,
                        verbose_name="Выбирать Автостоянка",
                    ),
                ),
                ("first_name", models.CharField(max_length=155, verbose_name="ФИО")),
                ("last_name", models.CharField(max_length=155, verbose_name="Имя")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                (
                    "number",
                    models.CharField(max_length=25, verbose_name="Номер телефона"),
                ),
                ("comments", ckeditor.fields.RichTextField(verbose_name="Комментарий")),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=155, null=True, verbose_name="Скидка"
                    ),
                ),
                (
                    "add_options",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.addoptions",
                        verbose_name="Дополнительные опции",
                    ),
                ),
                (
                    "type_car",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.typecar",
                        verbose_name="Тип транспарта",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Бронирование",
            },
        ),
    ]
