# Generated by Django 4.2.7 on 2024-11-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_addoptions_typecar_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="entry_time",
            field=models.TimeField(verbose_name="Время входа"),
        ),
        migrations.AlterField(
            model_name="book",
            name="exit_time",
            field=models.TimeField(verbose_name="выход время"),
        ),
    ]
