# Generated by Django 4.2.7 on 2024-11-22 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_book_entry_time_alter_book_exit_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="exit_data",
        ),
        migrations.RemoveField(
            model_name="book",
            name="exit_time",
        ),
    ]
