# Generated by Django 4.2.7 on 2024-11-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_remove_book_exit_data_remove_book_exit_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"verbose_name_plural": "Бронирования"},
        ),
        migrations.RemoveField(
            model_name="book",
            name="add_options",
        ),
        migrations.RemoveField(
            model_name="book",
            name="type_car",
        ),
        migrations.AlterField(
            model_name="book",
            name="comments",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="book",
            name="discount_code",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Код скидки"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="entry_date",
            field=models.DateTimeField(verbose_name="Дата входа"),
        ),
        migrations.AlterField(
            model_name="book",
            name="first_name",
            field=models.CharField(max_length=155, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="book",
            name="last_name",
            field=models.CharField(max_length=155, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="book",
            name="select_parking",
            field=models.CharField(max_length=155, verbose_name="Выбрать парковку"),
        ),
    ]
