# Generated by Django 4.2.7 on 2024-11-22 01:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_servicespage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Solutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155, verbose_name="Заголовка")),
                (
                    "descriptions",
                    ckeditor.fields.RichTextField(verbose_name="Описание"),
                ),
                (
                    "title_car",
                    models.CharField(max_length=155, verbose_name="Заголовка машины"),
                ),
                (
                    "descriptions_car",
                    ckeditor.fields.RichTextField(verbose_name="Описание машины"),
                ),
                (
                    "title_service",
                    models.CharField(max_length=155, verbose_name="Заголовка Услуги"),
                ),
            ],
            options={
                "verbose_name_plural": "Наши решение",
            },
        ),
    ]
